### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jmatsushita** [sighjs/sigh#39]
I'm getting this error message without further information...
```
$ sigh build-test -vvvvv
 * running pipelines [ build-test ] with 3 jobs
 * waiting for subprocesses to start
 * subprocesses started in 0.852 seconds
 ! error: pipeline build-test
 ! TypeError: Cannot read property 'map' of undefined
 * pipeline(s) complete: 4.103 seconds
```

It happens with a large file tree and I think in the write plugin.

**Comment by jmatsushita** [comment]
Ok I've isolated this strange problem but I'm not sure yet what's causing it:

```
source
├── css
│   └── two.css
└── one.md
```

```
  pipelines['build-css'] = [
    glob({ basePath: 'source' }, '**/*.*'),
    debug(),
    write('dest')
  ]
```

```
$ sigh build-css
add: source/css/two.css
add: source/one.md
 ! error: pipeline build-css
 ! TypeError: Cannot read property 'map' of undefined
```

**Comment by jmatsushita** [comment]
Seems like this line https://github.com/sighjs/sigh/blob/master/src/plugin/write.js#L63 is throwing the error.

**Comment by ohjames** [comment]
I have a fix almost ready for this, coincidentally someone raised it today but via a different manifestation.

**Comment by ohjames** [comment]
This should be fixed in the latest version, let me know if it isn't and I can apply this PR. Thanks!

**Comment by joelanders** [comment]
jmatsushita's fix in his PR works for me.

**Comment by ohjames** [comment]
@joelanders and the latest version of sigh with the latest sigh-core peer dependency does not?

**Comment by ohjames** [comment]
@joelanders I think @jmatsushita's patch is wrong and will break source maps in other instances.

**Comment by jmatsushita** [comment]
I confirm that my patch is wrong and also that the latest version (sigh@0.12.28 ) doesn't solve the problem with the [test above](#issuecomment-210036070)

**Comment by ohjames** [comment]
Ah this is a duplicate of https://github.com/sighjs/sigh-core/issues/3
